# Security Commands Configuration

# Blocked command patterns (immediate rejection)
blacklist_patterns:
  # Dangerous system operations
  - '\brm\s+-rf\s+/'
  - '\brm\s+'
  - '\bmv\s+.*/'
  - '\bcp\s+.*>/dev/'
  - '\bdd\s+if='
  - '\bmkfs\.'
  - '\bformat\b'
  - '\b:(){:|:&};:'
  - '\bchmod\s+777'
  - '\bchmod\s+'
  - '\bchown\s+root'
  
  # Privilege escalation
  - '\bsudo\b'
  - '\bsu\b'
  - '\bdoas\b'
  
  # Remote code execution
  - '\bwget.*\|\s*bash'
  - '\bcurl.*\|\s*sh'
  - '\beval\s*\('
  - '\bexec\s*\('
  - '\b__import__'
  
  # Network/Firewall manipulation
  - '\biptables\s+-F'
  - '\bufw\s+disable'
  
  # Process manipulation
  - '\bkill\s+-9\s+1'
  - '\bkillall\s+-9'
  
  # System shutdown/reboot
  - '\bshutdown'
  - '\breboot'
  - '\bhalt\b'
  - '\bpoweroff'
  
  # User management
  - '\buseradd'
  - '\buserdel'
  - '\bpasswd'
  
  # Disk operations
  - '\bcryptsetup'
  - '\bfdisk'
  - '\bparted'
  
  # Dangerous network tools
  - '\bnc\s+.*-e'
  - '\bncat\s+.*-e'
  - '\bsocat.*exec'
  - '\bssh\s+.*@'
  - '\bscp\s+'
  - '\brsync\s+'
  
  # Dangerous archive operations
  - '\btar\s+.*--exclude=/'
  - '\bgit\s+clone.*--mirror'

# System commands (basic utilities)
system_commands:
  - cat
  - less
  - more
  - head
  - tail
  - grep
  - find
  - locate
  - ls
  - pwd
  - whoami
  - id
  - uname
  - hostname
  - env
  - awk
  - sed
  - cut
  - sort
  - uniq
  - wc
  - tr
  - strings
  - file
  - hexdump
  - xxd
  - base64
  - echo
  - printf
  - curl
  - wget

# Pentesting tools
pentest_commands:
  - ping
  - traceroute
  - dig
  - nslookup
  - host
  - whois
  - nmap
  - rustscan
  - masscan
  - ffuf
  - gobuster
  - dirsearch
  - nikto
  - whatweb
  - searchsploit
  - msfconsole
  - metasploit
  - nuclei
  - nc
  - netcat
  - telnet
  - hydra
  - john
  - hashcat
  - amass
  - subfinder
  - assetfinder
  - sublist3r

# Protected filesystem paths (cannot be modified)
protected_paths:
  - /
  - /bin
  - /boot
  - /dev
  - /etc
  - /lib
  - /lib64
  - /proc
  - /root
  - /sbin
  - /sys
  - /usr
  - /var/log

# Execution limits
limits:
  command_timeout: 60

# Security headers for web pentesting
security_headers:
  Strict-Transport-Security: "Enforces HTTPS connections"
  Content-Security-Policy: "Prevents XSS and injection attacks"
  X-Content-Type-Options: "Prevents MIME-type sniffing"
  X-Frame-Options: "Prevents clickjacking"
  X-XSS-Protection: "Enables XSS filter in browser"
  Referrer-Policy: "Controls referrer information"
  Permissions-Policy: "Controls browser features"