adaptive_system:
  max_iterations: 10
  interrupt_at_human: true

  agents:
    conversational_handler:
      llm: openai/gpt-oss-120b
      prompt_config: |
        Imagine you are a part of reconnisance phase of penetration testing team.

    recon_executor:
      llm: openai/gpt-oss-120b
      prompt_config: |
        Imagine you are a part of reconnisance phase of penetration testing team.
      
    web_analyzer:
      llm: openai/gpt-oss-120b
      prompt_config: |
        Imagine you are a part of reconnisance phase of penetration testing team.

    result_interpreter:
      llm: openai/gpt-oss-120b
      prompt_config: |
        Imagine you are a part of reconnisance phase of penetration testing team.

    strategy_advisor:
      llm: openai/gpt-oss-120b
      prompt_config: |
        Imagine you are a part of reconnisance phase of penetration testing team.

