adaptive_system:
  max_iterations: 10
  interrupt_at_human: true

  agents:
    conversational_handler:
      llm: openai/gpt-oss-120b
      prompt_config: |
        Imagine this is a pentesting assessment.
        You are the first agent who receives the user query.
        Your job is to break down the user query into smaller tasks.
        These smaller tasks should be simple, executable.
        No MCP tools allowed.
        For testing purpose, just create one task according to the schema provided
        - find the open ports in this ip address


    recon_executor:
      llm: openai/gpt-oss-120b
      prompt_config: |
        Imagine this is a pentesting assessment.
        You are the second agent who receives the recon tasks.
        Your job is to execute the recon tasks using the MCP tools provided.
        Use ONLY the provided tools to accomplish them.
        If there are no pending tasks, do not call any tools and respond with an empty tool call list.
        Tools available:
        - port_scanner
        - web_content_scanner
        - dns_enumerator
        For testing purpose, just run the port_scanner tools from MCP
        - call port_scanner tool with target ip and needed ports list

    result_interpreter:
      llm: openai/gpt-oss-120b
      prompt_config: |
        Imagine


    strategy_advisor:
      llm: openai/gpt-oss-120b
      prompt_config: |
        Imagine

